### PR TITLE
Add python type hints and mypy static type checker

### PR DESCRIPTION
**Pull request by rednar**
Relates to issue: #599 

Add python type hint to cement.core, ext, util and cli.  
Couldn't reach 100% coverage inside ext_argparse#427 within a special case of `stacked_type="embedded"`. Would be great if you can have a look at this @derks.

This enables intelli-sense support within IDEs. Adds additional safety especially for Interface functions.
I changed some interfaces related to inconsistant argument lists but tried to make no logical changes.

### CODE REVIEW

**Comment by derks** [comment]
@rednar this is a really excellent effort to introduce typing. As there are a lot of changes here I will need some time to review, but thank you for working on this.

**Comment by rednar** [comment]
Appreciate it - take your time and get back to me when there are questions.
You may have a look at these changes which are not quite trivial:
- OutputInterface.render returns non-optional 'str' Therefore DummyOutputHandler changed. Same for TemplateInterface
- Introduced inheritence of the Meta class (down to Handler, not Interface) in order to get better IDE support of the _meta object.
- Introduced CommandMeta within ext_argparse.py as transport object replacing the dict (type safety)
- I will try switching the individual settings of mypy to its 'strict' option instead. I just stumbled over this which sounds better than having a bunch of arbitrary settings enabled.

**Comment by derks** [comment]
@rednar just wanted to let you know this is still on my radar... I apologize it's taken a while.

**Comment by derks** [comment]
@rednar this is a bit PR, and will not merge it directly as I need to walk through each commit to ensure all the things. That said, this is a tremendous help toward getting Cement fully typed, and I will be using this as my road map toward that. As a starting point I've added the configs for `mypy`, and added `comply-typing` to make helpers so that I can begin working toward this bit by bit.

**Comment by derks** [comment]
@rednar I am happy to say that all of the work that you've done for typing is now complete, and merged into `main`. Because of your hard work, Cement 3 now has typing and by default `make test` now enforces MyPy compliance before tests will run. 

```
LOG:  Loaded graph with 434 nodes (0.943 sec)
LOG:  Found 256 SCCs; largest has 44 nodes
LOG:  256 fresh SCCs (434 nodes) left in queue (and will remain unprocessed)
LOG:  Build finished in 0.977 seconds with 0 modules, and 0 errors
Success: no issues found in 51 source files
```


I can't thank you enough for this effort.  If you have any kind of Patreon/TipJar/Buy me a coffee/Etc type sponsorship service please reach out, as I would like to spot you something for all of your time on this.

**Pull request closed without merging**
