### PR TITLE
Enable generator based hooks as per issue #296

### PR DESCRIPTION
**Pull request by fxstein**
Enable the use of generator based hooks in cement as per issue #296

### CODE REVIEW

**Comment by fxstein** [comment]
Hmm - thought I have the CI enabled on my fork, but missed this one. Will take a look tonight what I must have missed.

**Comment by fxstein** [comment]
This solution is now compatible with all supported versions of python. Gonna see how to add a valid test case for hooks as generators.

**Comment by fxstein** [comment]
Generator based hook tests added.

**Comment by fxstein** [comment]
Squashed all commits into a single one. This should be ready to go.

**Comment by derks** [comment]
Could you supply a minimum example of how you would use this?  The idea isn't bad, just adds another layer of complexity that I want to be clear is really necessary.

**Comment by fxstein** [comment]
Sure thing.

Here is a simple example:

Write an asyncio webserver that processes incoming REST/JSON events multithreaded. Allow plugins to provide hooks that can introduce special processing or event rules.

The main engine could have the following async co-routine:

````
    @asyncio.coroutine
    def process_event(self, event_type, event):
        self.log.debug('process_event() Event: %s %s' % (event_type, event))

        # Enable plugins to define state/status caches specific to
        # one or more event types
        for res in hook.run('process_event', self, event_type, event):
            pass

        time4 = time.time()*1000

        # Report final event processing latency
        self.log.info('Event Processing Final Latency: %2.4sms' %
                      (time4 - event['shtime1']))
````

and a plugin can register the various defined hooks:

````
def load(app):
    hook.register('process_event', myplugin_process_event)

    app.log.info('Succeful Rules Plugin registration', __name__)
````

and then implement its own event processor like that:

````
@asyncio.coroutine
def myplugin_process_event(app, event_type, event):
    app.log.debug('process_event() Event: %s %s' %
                  (event_type, event), __name__)

    # Wait some time or perform other async functions
    yield from asyncio.sleep(5)
````

Async coroutines are almost always generators. Hope this helps!

You can find a more complete example here:
https://github.com/fxstein/SentientHome/blob/rules/engine/event.engine.py

and an example plugin:
https://github.com/fxstein/SentientHome/blob/rules/rules/plugin.rules.py

This allows an async based webserver to accept incoming events and process plugin defined hooks async. That means the sever can return a 200 OK right away (within a few ms) while custom rules might run for extended periods of time (ms to days)

Hope this helps!

**Comment by fxstein** [comment]
I should have mentioned what happens when you make the hook NOT an @asyncio.coroutine:

All processing will happen inline (even if you call it from an asyncio webserver). That means that any blocking or waiting will block the entire webserver for that amount of time.

**Comment by fxstein** [comment]
Any updates on this? Thanks!

**Comment by derks** [comment]
@fxstein I apologize, I have not had a chance to evaluate this.  It is a relatively simple change, and appears to maintain backward compatibility so it shouldn't be a problem, I just need a few minutes to really dig into it.  Hopefully this week.

**Comment by fxstein** [comment]
Polite bump...

**Comment by derks** [comment]
@fxstein appreciate your patience, and the reminder.  Day job has not left me much time to work on Cement... but hoping to change that up soon (scheduling time in my calendar now to ensure development moves forward every week).

**Comment by fxstein** [comment]
Thank you!

**Pull request merged**
