### PR TITLE
allow jinja2 template inheritance Fixes #381

### LINKED ISSUE #381: Allow Jinja templates inheritance
Template inheritance with Jinja requires its environment to have defined a loader.

For regular template rendering, we don't need it since Cement loads the templates content his own way. But internally Jinja can't rely on cement.core.output.TemplateOutputHandler._load_template()

The idea is to set the Jinja loader at _setup time, based on the app settings:
* FileSystemLoader if template_dirs is defined
* else, PackageLoader if template_module is defined

If none of them is defined, we don't set the loader, but in any case we expose Jinja Environment as self.app.output.env so that we can manipulate it in our application.

PR coming shortly...

### PR DESCRIPTION
**Pull request by zacbri**

### CODE REVIEW

**Comment by derks** [comment]
As is this can't be merged as CementApp supports **both** `template_dirs` and `template_module` (not either/or).

**Comment by zacbri** [comment]
Ok i'll rework it
Le 7 juil. 2016 9:00 PM, BJ Dierkes <notifications@github.com> a écrit :As is this can't be merged as CementApp supports both template_dirs and template_module (not either/or).

**Comment by zacbri** [comment]
Hey @derks 

Just to make what I'm trying to achieve clearer: this change does not affect the initial template loading (referenced in self.app.render()), only loading of parent templates referenced via {% extends %} in the initial Jinja template.

Setting the Jinja loader in the extension based on where the initial template was found (dirs or module) is rather opinionated I agree, since it would only allow inheritance from the same location.  
But exposing the Jinja Environment allows the user to change the loader as needed (and other Environment parameters for that matters).

Another approach would be to just expose the Environment and leave the loader setup to the user.

I'm pushing a new commit with a more flexible approach based on the first option above. But it involves a small change to output.TemplateOutputHandler.  
Let me know what you think.

**Comment by zacbri** [comment]
Done.

on a side note, it looks like ther's now a dependency on `configobj` that is missing from requirements.txt

**Comment by derks** [comment]
ConfigObj is now required to run tests, yes... but not required by `cement.core`.

**Pull request merged**
