### PR TITLE
added jinja2 output handler

### PR DESCRIPTION
**Pull request by zacbri**
Was there a reason jinja2 was not supported as an output handler ?

### CODE REVIEW

**Comment by derks** [comment]
Been meaning to build this one for a while!  Thank you for the pull-request.  It looks clean, so I will test it out and merge it in shortly.

**Comment by zacbri** [comment]
Thanks.

I see it fails on python 3.2
Seems to be caused by the % syntax that was removed for strings then re-added in 3.3 (see http://stackoverflow.com/questions/8679985/unicode-strings-syntax-in-python).

How do you want me to handle this ? I can remove the utf8 test if you'd prefer.

**Comment by zacbri** [comment]
actually, using format() might fix it, let's see how it goes...

**Comment by zacbri** [comment]
no luck... I've just removed the test for now

**Comment by zacbri** [comment]
damn... any suggestions?

**Comment by derks** [comment]
Most likely due to the use of the unicode `u` prefix.  I believe it was removed in Python 3.2, then re-added in 3.3 .... however all strings are treated as unicode in Python 3 so it isn't necessary.  For Python 2.x it would be... I'd do something like this: If Python < 3, wrap it in `unicode()`, if >=3 wrap it in `str()`?

**Comment by zacbri** [comment]
Actually, even with that the tests will fail on 3.2.  
If you check the output of the last tests, it triggers syntax errors from within Jinja (still unicode). It seems to be caused by Jinja 2.8 being installed as a dependency of Sphinx (needs jinja2>=2.3), but support for Python 3.2 was dropped in Jinja 2.7.

I see 2 options:
* Explicitly install Jinja2==2.6 in Travis before_script and tune the tests based on Python version as suggested to avoid using unicode strings in 3.2
* Skip jinja testing for python 3.2 altogether. Rather opinionated I agree...

Let me know what you think

**Comment by derks** [comment]
Hrm.  Ok, will try and check this out today.  Won't be the first time we've had to hack around oddities like this.  Primary reason to care about Python 3.2 is if any OS Distros still package that version (which I'm not sure which do).

**Comment by derks** [comment]
Looks like Ubuntu 12.04 ships with Python 3.2.x ... getting a Vagrant box setup now to test it there to figure out how to work around it.

**Comment by zacbri** [comment]
ok I'll give it a go as well

**Comment by zacbri** [comment]
Hi @derks  
I've been trying to setup a dev env on Ubuntu 12.04, but I'm having a hell of a time even installing the dependencies. It looks like most of them aren't supporting python3.2 (at least the versions in Pipy).  
I've been able to go with the OS versions for some, but I'm getting stuck on "tabulate".

Any luck on your end ?  
BTW, Ubuntu 12.04 is EOL, perhaps it's not that big a deal not to support it ;)

**Comment by derks** [comment]
I had the same issue trying to get it running yesterday.  I only used Ubuntu 12.04 as an example because it included a version of Python 3.2.  The failures shouldn't have anything to do with ubuntu as all the deps are trying to install via PIP, however this all makes me wonder how in the hell Python 3.2 has been passing in Travis CI at all up until this issue?  No clue... but it's looking like support for 3.2 might get axed to move forward here.  Going to try one more thing, then move on and will merge this in (and drop 3.2 most likely).

**Comment by derks** [comment]
Should now going through after Issue #372.

**Comment by zacbri** [comment]
hey @derks 
thanks for merging. Do you have any ETA on the next release ?

**Comment by derks** [comment]
No firm ETA but I always work in clusters... so once I start committing/merging, I generally try to release within a week or two.  Also, can you make sure you add yourself to the CONTRIBUTORS file?

**Comment by zacbri** [comment]
Ok sounds good, thanks.
I'll make a PR for the CONTRIBUTORS file

**Pull request merged**
