### PR TITLE
fix deprecated imp usage (#386)

### PR DESCRIPTION
**Pull request by sigma67**
**NOTICE:** Prior to submitting a pull request, please ensure you abide by the
[Guidelines for Code Contributions], including but not limited to:

- PR is associated with at least one issue
- Submit from a **topic** branch, not a pre-existing Cement branch
- Make every effort to comply with [PEP8]
- All tests pass successfully
- Coverage reports 100% code coverage

---

**Issue:** #386

[Guidelines for Code Contributions]: https://github.com/datafolklabs/cement/blob/master/.github/CONTRIBUTING.md#guidelines-for-code-contributions
[PEP8]: http://www.python.org/dev/peps/pep-0008/

### CODE REVIEW

**Comment by sigma67** [comment]
Hi @derks, it seems the tests are passing except for some unrelated failures.

We also released this version internally and tested with our cement app under 3.12 and everything is working as expected.

**Comment by jonlowrey** [comment]
Hello @sigma67 and @derks,

Is there a scheduled release date for this fix? 

I'm running into issues with the above mentioned aws-elasticbenastalk package via the [aws-elastic-beanstalk-cli](https://github.com/aws/aws-elastic-beanstalk-cli/issues/493) which we use for our deployment. Downgrading to 3.11 does fix my issue in the short term. 

Thank you both for [maintaining critical infrastructure.](https://xkcd.com/2347/)

**Comment by sigma67** [comment]
I haven't heard anything from @derks in a while. We've released the package internally with the fix and it's working fine for us.

For release use `make dist` and `make dist-upload` and adjust for your own package server (after adjusting the version in the source)

**Comment by derks** [comment]
Thank you all for the feedback and effort in the PR. Due to starting a new job a few months ago I've been distracting and apologize for missing this. As the PR is tested and in use I'll look at this ASAP.

**Comment by sigma67** [comment]
Hi @derks, I have noticed an issue with my implementation that was causing `DeprecationWarnings` yet again.

So perhaps it was good to wait so long ;)

**Comment by derks** [comment]
Many thanks @sigma67 ... FWIW, I am planning to sprint this week and this is top of the list.

**Comment by derks** [comment]
@sigma67 @jonlowrey this has been merged to main. All tests pass on Python 3.7+ so it can roll out to next stable/3.0 release (after this current holiday sprint).

Thank you @sigma67 for your work on this... it is very much appreciated.

**Comment by sigma67** [comment]
@derks for sure! glad you found the time to merge

**Pull request merged**
